### PR TITLE
Fix ToC breaking documents with empty h* elements

### LINKED ISSUE #1042: Can't edit document after using an empty headline
I create a new document with an empty headline tag, like this:

```
Testing

##
Testing
```

Now closing the document and reopen it, it can't be edited anymore.

Chrome has following error message:

```
Uncaught ReferenceError: i is not defined
    at Toc.recursiveToc [as _createTocContent] (3.index.754ae252e09735e35e65.js:2)
    at Toc._init (3.index.754ae252e09735e35e65.js:2)
    at new Toc (3.index.754ae252e09735e35e65.js:2)
    at exports.generateToc (3.index.754ae252e09735e35e65.js:1)
    at updateViewInner (3.index.754ae252e09735e35e65.js:2)
    at hr (eval at module.exports (3.index.754ae252e09735e35e65.js:1), <anonymous>:2:22193)
    at Go.operation (eval at module.exports (3.index.754ae252e09735e35e65.js:1), <anonymous>:6:6208)
    at 3.index.754ae252e09735e35e65.js:2
    at invokeFunc (3.index.754ae252e09735e35e65.js:2)
    at trailingEdge (3.index.754ae252e09735e35e65.js:2)
```

I'm using CodiMD 1.2.1

### PR DESCRIPTION
**Pull request by SISheogorath**
Right now, the ToC has an undefined variable i that was an index in the 
original ToC code. Since the major rewrite in 
4fe062085324c50f2cfa062258559cf31858ef5f it's a recursive function 
without this index. The variable `i` was wrongly copied into its current 
place from the old code.

This patch replaces the variable `i` with the index of the header 
element. Fix the undefined variable problem.

Fixes #1042

### CODE REVIEW

**Comment by jackycute** [comment]
There's still an error when trying the snippet from the referenced issue.

```
md-toc.js?fd87:78 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at recursiveToc (VM61906 543:78)
    at Toc.recursiveToc [as _createTocContent] (VM61906 543:101)
    at Toc._init (VM61906 543:25)
    at new Toc (VM61906 543:20)
    at generateToc (VM61610 327:1633)
    at updateViewTocInner (index.js?3ba3:1591)
    at invokeFunc (debounce.js?3b82:95)
    at trailingEdge (debounce.js?3b82:142)
    at timerExpired (debounce.js?3b82:130)
```

File: public/vendor/md-toc.js [hunk 1]
```diff
@@ -74,8 +74,8 @@
         var elementText = (typeof this.process === 'function' ? this.process(element) : element.innerHTML).replace(/<(?:.|\n)*?>/gm, '')
         var id = element.getAttribute('id')
         if (!id) {
-          element.setAttribute('id', 'tip' + i)
-          id = '#tip' + i
+          element.setAttribute('id', 'tip' + this.elTitleElements.indexOf(element))
```
Comment (jackycute) [inline public/vendor/md-toc.js]:
```suggestion
          element.setAttribute('id', 'tip' + titleElements.indexOf(element))
```

File: public/vendor/md-toc.js [hunk 2]
```diff
@@ -74,8 +74,8 @@
...
+          id = '#tip' + this.elTitleElements.indexOf(element)
```
Comment (jackycute) [inline public/vendor/md-toc.js]:
```suggestion
          id = '#tip' + titleElements.indexOf(element)
```

**Comment by SISheogorath** [comment]
@jackycute Please have another look. The changes I made re-work the whole thing. I already noticed that it's broken (which is why it isn't merged yet), just didn't find the time to fix it finally. Thanks for the heads up, this should finally fix it.

File: public/js/index.js [hunk 3]
```diff
@@ -2786,6 +2786,7 @@ function updateViewInner () {
   renderTOC(ui.area.markdown)
   generateToc('ui-toc')
   generateToc('ui-toc-affix')
+  autoLinkify(ui.area.markdown)
```
Comment (jackycute) [inline public/js/index.js]: Hmm, why here calls `autoLinkify` again?

Comment (SISheogorath) [reply public/js/index.js]: Because ToC adds those `tip<number>` ids. Autolinkify in first place adds ids to all headers. At this point in time the `tip` ids, don't exist. So the anchors will link to `#`. Calling it twice is actually a dirty hack but fixes the problem of anchors that point into nowhere and makes emtpy header linkable. (using the ids, generated by ToC)

Comment (jackycute) [reply public/js/index.js]: That's ok.

File: public/js/extra.js [hunk 4]
```diff
@@ -845,12 +845,14 @@ const linkifyAnchors = (level, containingElement) => {
   for (let i = 0, l = headers.length; i < l; i++) {
     let header = headers[i]
     if (header.getElementsByClassName('anchor').length === 0) {
-      if (typeof header.id === 'undefined' || header.id === '') {
-                // to escape characters not allow in css and humanize
+      if ((typeof header.id === 'undefined' || header.id === '')) {
```
Comment (jackycute) [inline public/js/extra.js]: Maybe the parenthesis are not necessary here?

Comment (jackycute) [reply public/js/extra.js]: Oh, it might because the consistence you want to align with below code?

File: public/js/extra.js [hunk 5]
```diff
@@ -845,12 +845,14 @@ const linkifyAnchors = (level, containingElement) => {
...
+        // to escape characters not allow in css and humanize
         const id = slugifyWithUTF8(getHeaderContent(header))
         header.id = id
       }
-      header.insertBefore(anchorForId(header.id), header.firstChild)
+      if (!(typeof header.id === 'undefined' || header.id === '')) {
```
Comment (jackycute) [inline public/js/extra.js]: I think this block can simplify with `if (...) {...} else {...}`

File: public/js/extra.js (hunk 4 above)
Comment (SISheogorath) [reply public/js/extra.js]: Nope, they were actually just left from experiments. Fixed.

File: public/js/extra.js (hunk 5 above)
Comment (jackycute) [reply public/js/extra.js]: Got it

**Comment by jackycute** [comment]
Could you share your test snippet @SISheogorath ?

**Comment by SISheogorath** [comment]
Looked like this:

<details>

# Testing

some lorem ipsum

##
Testing

##
more testing

</details>

**Comment by jackycute** [comment]
Thanks @SISheogorath, I think it's good to go.
