### PR TITLE
fix: login email should be case insensitive

### LINKED ISSUE #1744: email lowercase
when checking for the password the email should be put through tolowercase before comparing because no one remembers when one used upper and lowercase and as it doesnt matter in emails what you spell upper and lower case; most services ignore that already and so should codimd.

### PR DESCRIPTION
**Pull request by DubMythlit**
fix #1744
By query email in lower case makes login be case insensitive now
tested on: Postgres12 & sqlite3

### CODE REVIEW

File: lib/auth/email/index.js [hunk 1]
```diff
@@ -21,7 +22,11 @@ passport.use(new LocalStrategy({
   try {
     const user = await models.User.findOne({
       where: {
-        email: email
+        email: sequelize.where(
+          sequelize.fn('LOWER', sequelize.col('email')),
+          'LIKE',
```
Comment (jackycute) [inline lib/auth/email/index.js:27]: I don't think we need to use LIKE operator here, compare directly will be fine.

**Comment by jackycute** [comment]
Hi @Dubmyhtlit,

Thanks for your PR,
Please also sign off your commit like this:

```
commit message

Signed-off-by: XXX <xxx@example.com>
```

**Comment by Yukaii** [comment]
@DubMythlit You have to signoff every commit:

```bash
git rebase --signoff -i develop
```

**Review by Yukaii — APPROVED** [review]
